### ISSUE TITLE
s6-networking as build-deps

### ISSUE THREAD

**Issue by matthewhembree** [sedunne/docker-gophernicus#1]
This doesn't work.

s6-networking is a build-dep that you're removing after the build; before running the super daemon s6-tcpserver.

I guess you could copy the 's6-tcpserver' binary to /sbin before 'apk del'. Assuming that it's a standalone binary that doesn't depend on the other members of the s6-networking package.

Thanks!

**Comment by matthewhembree** [comment]
Nope, there's libraries in the s6-networking package. ~454k.

Thanks!

**Comment by sedunne** [comment]
Thanks for reporting this!

I just pushed an update that should resolve this, as well as other issues I've had in the past (might take a bit for the build to finish on docker hub). Admittedly I never really had this working 100%, but largely just thought it to be my own lack of knowledge on gohper and gophernicus.

That said, I've now got a basic gopher site working (aside from the default gophermap that the container uses), and have updated the README about setting the hostname when running the container.

If you happen to run into any other issues, please let me know.
